Navbar feature
WildCodeSchool/2023-02-js-btz-wild-note pull request #16
Opened 2023-04-20 08:05 UTC by guebrak

2023-04-20 08:13 UTC, ldupas requested changes

2023-04-20 08:13 UTC, ldupas commented on src/components/navbar/Navbar.css
> +
Supprimer les espacements inutiles

2023-04-21 10:00 UTC, piveteauit submitted a review, later dismissed

2023-04-21 10:27 UTC, Axelastach approved these changes

2023-04-21 11:47 UTC, piveteauit commented on src/components/navbar/Navbar.jsx
> +  const {pathname} = location;
Possible de simplifier les 2 constantes en déstructurant:

const {pathname} = useLocation();

2023-04-21 11:52 UTC, piveteauit requested changes
Simplify la lecture et l'utilisation du useLocation

2023-04-21 12:02 UTC, piveteauit approved these changes

2023-04-21 12:06 UTC, merged