Settings feature
WildCodeSchool/2023-02-js-btz-wild-note pull request #23
Opened 2023-04-26 13:37 UTC by Elolecroco

2023-04-26 13:38 UTC, justroxanne approved these changes

2023-04-26 13:53 UTC, piveteauit requested changes

2023-04-26 13:53 UTC, piveteauit commented on src/components/GenreSorting/GenreSorting.jsx
> +  const [genres, setGenre] = useState([]);
Ah ça non ^^, pluriel ou singulier mais le même pour les 2 svp

2023-04-26 13:55 UTC, Elolecroco commented on src/components/GenreSorting/GenreSorting.jsx
> +  const [genres, setGenre] = useState([]);
fait

2023-04-27 07:21 UTC, piveteauit approved these changes

2023-04-27 07:21 UTC, merged